### ISSUE TITLE
Missing handle.png to resize

### ISSUE THREAD

**Issue by Vrandus** [awSweeney/FFXIV-ACT-Rainbow-Mage-Overlays#10]
Just pulled your overlay and noticed that the handle.png to resize the window is missing?

I'm running the latest OverlayPlugin version (OverlayPlugin 0.17.4)

SS:
![image](https://user-images.githubusercontent.com/17153490/145757756-3514b660-8674-46da-b5fc-54191ec8e2fa.png)

**Comment by awSweeney** [comment]
Handle image path broken due to directory restructure. Pointed to correct location in CSS.

**Comment by awSweeney** [comment]
Fix applied to v1.1.2 package
