### ISSUE TITLE
PLEASE do not instruct people to install the version of overlayplugin that you are using in the readme!

### ISSUE THREAD

**Issue by MyTechnoHunter** [awSweeney/FFXIV-ACT-Rainbow-Mage-Overlays#17]
the version referenced in your readme file is out dated and has not been updated since 2015..

the correct way to install overlayplugin is to open ACT.. goto the plugins -> plugin listing tab, and in the upper right corner is a get plugins button.. choose the top of the resulting list of plugins 

![image](https://user-images.githubusercontent.com/55214545/146306514-1dfb9a78-d857-4fe4-a242-eeff2495859d.png)

this will install the latest overlayplugin (ngld is the dev)

from there you can click the new button on the overlayplugin dll tab, name the overlay you are adding and choose the custom preset with miniparse type then hit OK to save your overlay. then, click the overlay you just added, and click on the URL path (tripple dots to the right), browse to your extracted overlays from your release zip, and life goes on :) no problem

**Comment by awSweeney** [comment]
Thanks for pointing this out. I've been using the version I've had without issue for ages. Did not know this was an available option. Will get this updated.

**Comment by awSweeney** [comment]
Instructions updated and tagged in v1.2.1
