### ISSUE TITLE
How do I change size and opacity?

### ISSUE THREAD

**Issue by sauronshotdogs** [awSweeney/FFXIV-ACT-Rainbow-Mage-Overlays#19]
I am finding it hard to see what's going on, as it's almost completely transparent and very small

**Comment by awSweeney** [comment]
Hi @sauronshotdogs ,

There's a drag box in the lower right that will allow you to resize the table.

![19ebdae074](https://user-images.githubusercontent.com/5041783/147798823-6afc242d-b4e5-41c7-9cfd-6e5271b5e39a.png)


Can you post a screenshot with the transparency issue you're having? The BG version of the overlay might help.
